-- MySQL Script generated by MySQL Workbench
-- Mon Aug 23 20:06:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `capacity` INT NULL,
  `status` INT NULL,
  `comfort` INT NULL,
  `price` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`guests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `days_of_stay` INT NOT NULL,
  `date_check_in` DATE NULL,
  `date_check_out` DATE NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guests_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_guests_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `hotel`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(15,2) NULL,
  `guest_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_guests_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_guests`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel`.`guests` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
